<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>OOP_2._Dönem_Proje_Ödevi</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <StartupObject></StartupObject>
    <ApplicationIcon>heavy_metal_gold_icon_155280.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="heavy_metal_gold_icon_155280.ico" />
  </ItemGroup>

</Project>